
name: Model Select Test

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
    deploy:      
      name: Model Selector
      runs-on: ubuntu-latest
      environment: prod
      env:
        AZURE_OPENAI_DEPLOYMENT: ${{ vars.AZURE_OPENAI_DEPLOYMENT }}
        AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
        AZURE_OPENAI_ENDPOINT: ${{ vars.AZURE_OPENAI_ENDPOINT }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        MLFLOW_EXPERIMENT_NAME: ${{ vars.MLFLOW_EXPERIMENT_NAME }}
        MLFLOW_TRACKING_URI: ${{ vars.MLFLOW_TRACKING_URI }}
        HF_TOKEN: ${{ secrets.HUGGING_FACE_API_KEY }}
        HF_REPO: ${{ vars.HF_REPO }}

      steps:
        - uses: actions/checkout@v4

        - name: Install dependencies
          run: pip install --no-cache-dir --upgrade -r .github/requirements2.txt

        - name: Install Agent dependencies
          run: pip install --no-cache-dir --upgrade semantic-kernel==1.39.4

        - name: Model Selection
          run: python -m model_building.model_select
